stages:
  data:
    cmd: make data
    deps:
      - src/data/make_dataset.py
    outs:
      - data/raw

  prepare:
    cmd: make prepare
    deps:
      - data/raw/train.csv
      - src/prepare/prepare_data.py
    params:
      - dataset.target
      - prepare.random_state
      - prepare.split
      - prepare.missing.num_cols
      - prepare.missing.cat_cols
      - prepare.drop.cols
    outs:
      - data/prepared
  featurize:
    cmd: make featurize
    deps:
      - data/prepared/train.csv
      - data/prepared/test.csv
      - src/features/build_features.py
    params:
      - dataset.target
      - featurize.ohe_cols
    outs:
      - data/processed
  train:
    cmd: make train
    deps:
      - data/processed/train.joblib
      - src/models/train_model.py
    params:
      - train.seed
      - train.n_estimators
      - train.min_split
    outs:
      - model.joblib
  evaluate:
    cmd: make evaluation
    deps:
      - data/processed/test.joblib
      - src/models/evaluate_model.py
      - model.joblib
    metrics:
      - reports/scores.json:
          cache: false
    plots:
      - reports/prc.json:
          cache: false
          x: recall
          y: precision
      - reports/roc.json:
          cache: false
          x: fpr
          y: tpr
      - reports/cfm.json:
          cache: false
          template: confusion
          x: actual
          y: predicted
