name: CML

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get commit Sha
        run: |
          echo current_sha = ${{ github.sha }}
          echo current_ref = ${{ github.ref }}
          echo pull_event_number = ${{ github.event.number }}
          echo pull_request_number = ${{ github.event.pull_request.number }}
          echo pull_request_sha = ${{ github.event.pull_request.head.sha }}
          echo b = "$(gh pr list --repo Schots/mlops_project)"

      - name: CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "foo" > foo
          cml pr "foo"
      - name: CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" >> report.md
          cml send-comment --pr=85 --update report.md
